#!/usr/bin/env python3
"""Convert Macaulay2 certificate output into Lean files, one lemma per file.

Accepts either shape_certificates_sos.out ("CERT u=ustar v=<v> k=<k> m=<m>",
witness (u*·v)^k·(l1l2)^m) or shape_certificates_v3.out ("CERT v=<v> k=<k> m=<m> ...",
witness u*^k·v·(l1l2)^m).  Emits:

  ../Trinomial/ShapeCert/CertI.lean   (I = 1..6, one heavy linear_combination each)
  ../Trinomial/ShapeCertificates.lean (imports + the wrapper elimination_of_ne_zero)

One lemma per file keeps the peak memory of each Lean process small — this machine
has 16 GB and builds must run sequentially.
"""

import os
import re
import sys

USTAR = "r1^2 + s1^2 + r2^2 + s2^2"

GDECLS = """    (g0 : l1 + l2 - 1 = 0)
    (g1 : l1*r1 + l2*r2 = 0)
    (g2 : l1*(r1^2 - s1) + l2*(r2^2 - s2) = 0)
    (g3 : l1*r1*(r1^2 - 3*s1 + 2) + l2*r2*(r2^2 - 3*s2 + 2) = 0)
    (g4 : l1*(r1^4 - 6*r1^2*s1 + 8*r1^2 + 3*s1^2 - 6*s1)
      + l2*(r2^4 - 6*r2^2*s2 + 8*r2^2 + 3*s2^2 - 6*s2) = 0)"""

CERT_FILE = """import Mathlib.Tactic

/-!
Auto-generated by `certificates/gen_lean_certificates.py` from the Macaulay2
computation in `certificates/`; do not edit by hand.  See
`Trinomial/ShapeCertificates.lean` for context.
-/

set_option autoImplicit false

namespace Trinomial.ShapeCert

set_option maxRecDepth 65536 in
set_option maxHeartbeats 4000000 in
theorem cert{idx} (l1 l2 r1 s1 r2 s2 : ℚ)
{gdecls} :
    ({ustar})^{k} * ({v}) * (l1*l2)^{m} = 0 := by
  linear_combination
    ({c0}) * g0
    + ({c1}) * g1
    + ({c2}) * g2
    + ({c3}) * g3
    + ({c4}) * g4

end Trinomial.ShapeCert
"""

WRAPPER_HEADER = """{imports}

/-!
# Certificates for the trinomial classification (Proposition 2.4 (iii), Case 2)

**Auto-generated** by `certificates/gen_lean_certificates.py` from the Macaulay2
computation `certificates/shape_certificates_v3.m2`; do not edit by hand.

The paper's proof of Proposition 2.4 decomposes the saturation of the ideal of the
equations `(k=0) … (k=4)` at `λ₁λ₂` into two primes.  The per-file lemmas
`ShapeCert.cert1 … cert6` witness the containment corresponding to the affine prime
`P₂`: with `u* = r₁²+s₁²+r₂²+s₂²` (nonzero exactly in Case 2), each generator `v` of
the elimination ideal `P₂ ∩ ℚ[r₁,s₁,r₂,s₂]` satisfies an identity

  `u*^k · v · (λ₁λ₂)^m = Σᵢ hᵢ·gᵢ`

with explicit cofactors `hᵢ` (verified by `linear_combination`), so `v` vanishes on
every solution with `λ₁λ₂ ≠ 0 ≠ u*`.  The wrapper `elimination_of_ne_zero` packages
this for the classification proof.
-/

set_option autoImplicit false

namespace Trinomial.ShapeCert

/-- The five defining equations, as hypotheses shared by all certificates. -/
def eqs (l1 l2 r1 s1 r2 s2 : ℚ) : Prop :=
  l1 + l2 - 1 = 0 ∧
  l1*r1 + l2*r2 = 0 ∧
  l1*(r1^2 - s1) + l2*(r2^2 - s2) = 0 ∧
  l1*r1*(r1^2 - 3*s1 + 2) + l2*r2*(r2^2 - 3*s2 + 2) = 0 ∧
  l1*(r1^4 - 6*r1^2*s1 + 8*r1^2 + 3*s1^2 - 6*s1)
    + l2*(r2^4 - 6*r2^2*s2 + 8*r2^2 + 3*s2^2 - 6*s2) = 0

/-- **Case-2 elimination**: on a solution of the equations with `λ₁λ₂ ≠ 0` on which
not all of `r₁, s₁, r₂, s₂` vanish, the six generators of the elimination ideal of the
affine prime `P₂` vanish  [proof of Proposition 2.4, Case 2]. -/
theorem elimination_of_ne_zero (l1 l2 r1 s1 r2 s2 : ℚ) (hl1 : l1 ≠ 0) (hl2 : l2 ≠ 0)
    (hne : ¬(r1 = 0 ∧ s1 = 0 ∧ r2 = 0 ∧ s2 = 0)) (h : eqs l1 l2 r1 s1 r2 s2) :
    {conj} := by
  obtain ⟨g0, g1, g2, g3, g4⟩ := h
  have hu : r1^2 + s1^2 + r2^2 + s2^2 ≠ 0 := by
    intro hzero
    exact hne ⟨by nlinarith [sq_nonneg r1, sq_nonneg s1, sq_nonneg r2, sq_nonneg s2],
      by nlinarith [sq_nonneg r1, sq_nonneg s1, sq_nonneg r2, sq_nonneg s2],
      by nlinarith [sq_nonneg r1, sq_nonneg s1, sq_nonneg r2, sq_nonneg s2],
      by nlinarith [sq_nonneg r1, sq_nonneg s1, sq_nonneg r2, sq_nonneg s2]⟩
  have hll : l1 * l2 ≠ 0 := mul_ne_zero hl1 hl2
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_⟩
{branches}
end Trinomial.ShapeCert
"""

BRANCH = """  · have hc := cert{idx} l1 l2 r1 s1 r2 s2 g0 g1 g2 g3 g4
    have hA : ({ustar})^{k} ≠ 0 := pow_ne_zero _ hu
    have hB : (l1*l2)^{m} ≠ 0 := pow_ne_zero _ hll
    rcases mul_eq_zero.mp hc with h' | h'
    · rcases mul_eq_zero.mp h' with h'' | h''
      · exact absurd h'' hA
      · exact h''
    · exact absurd h' hB
"""


def split_cofactors(s: str):
    inner = s.strip()
    m = re.match(r"matrix \{\{(.*)\}\}", inner)
    if not m:
        sys.exit(f"bad cofactor line: {s[:80]}")
    parts = [p.strip() for p in m.group(1).split(",")]
    if len(parts) != 5:
        sys.exit(f"expected 5 cofactors, got {len(parts)}")
    return parts


def parse(src):
    lines = open(src).read().splitlines()
    certs = []
    i = 0
    while i < len(lines):
        mm = re.match(r"CERT (?:u=ustar )?v=(.*?) k=(\d+) m=(\d+)", lines[i])
        if mm:
            cofs = split_cofactors(lines[i + 1].split("cofactors=", 1)[1])
            certs.append((mm.group(1), mm.group(2), mm.group(3), cofs))
            i += 2
        else:
            i += 1
    if len(certs) != 6:
        sys.exit(f"expected 6 certificates, found {len(certs)}")
    return certs


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "shape_certificates_v3.out"
    certs = parse(src)
    os.makedirs("../Trinomial/ShapeCert", exist_ok=True)
    for idx, (v, k, m, cofs) in enumerate(certs, 1):
        body = CERT_FILE.format(idx=idx, gdecls=GDECLS, ustar=USTAR, v=v, k=k, m=m,
                                c0=cofs[0], c1=cofs[1], c2=cofs[2], c3=cofs[3],
                                c4=cofs[4])
        open(f"../Trinomial/ShapeCert/Cert{idx}.lean", "w").write(body)
    imports = "\n".join(f"import Trinomial.ShapeCert.Cert{i}" for i in range(1, 7))
    conj = " ∧\n    ".join(f"{v} = 0" for (v, _, _, _) in certs)
    branches = "".join(
        BRANCH.format(idx=idx, ustar=USTAR, k=k, m=m)
        for idx, (v, k, m, _) in enumerate(certs, 1))
    open("../Trinomial/ShapeCertificates.lean", "w").write(
        WRAPPER_HEADER.format(imports=imports, conj=conj, branches=branches))
    print(f"wrote 6 cert files + wrapper from {src}")


if __name__ == "__main__":
    main()
