import Mathlib.Computability.Primrec.Basic
import TrinomialUndecidability.Computability.MathlibDiophantineSequence

/-!
# The primitive-recursive induction boundary for mathlib Diophantine functions

This module discharges every constructor of `Nat.Primrec` except the genuinely
number-theoretic bounded-sequence step.  For primitive recursion it defines an explicit
beta-coded computation relation and proves both directions of its semantics using
`Nat.beta_unbeta_coe`.  Consequently one sharply stated closure fact--Diophantineness of
the bounded beta transition conjunction--implies that every unary primitive-recursive
function is Diophantine.
-/

set_option autoImplicit false

namespace TrinomialUndecidability.Computability.MathlibDiophantinePrimrec

open Dioph Fin2 Nat
open Vector3
open scoped Dioph Vector3

open TrinomialUndecidability.Computability.MathlibDiophantinePairing
open TrinomialUndecidability.Computability.MathlibDiophantineSequence

/-- Unary natural functions viewed through mathlib's one-coordinate `DiophFn` API. -/
def NatDiophFn (function : ℕ → ℕ) : Prop :=
  DiophFn fun values : Vector3 ℕ 1 ↦ function (values &0)

/-- The value sequence generated by one primitive-recursion step. -/
def recursionValue (base step : ℕ → ℕ) (parameter : ℕ) : ℕ → ℕ
  | 0 => base parameter
  | index + 1 =>
      step (Nat.pair parameter (Nat.pair index
        (recursionValue base step parameter index)))

/-- The unary function produced by the `Nat.Primrec.prec` constructor. -/
def primitiveRecursion (base step : ℕ → ℕ) (input : ℕ) : ℕ :=
  recursionValue base step (Nat.unpair input).1 (Nat.unpair input).2

private theorem recursionValue_eq_natRec (base step : ℕ → ℕ)
    (parameter length : ℕ) :
    recursionValue base step parameter length =
      length.rec (base parameter)
        (fun index previous ↦
          step (Nat.pair parameter (Nat.pair index previous))) := by
  induction length with
  | zero => rfl
  | succ length ih => simp [recursionValue, ih]

theorem primitiveRecursion_eq_unpaired (base step : ℕ → ℕ) :
    primitiveRecursion base step =
      Nat.unpaired fun parameter length ↦
        length.rec (base parameter)
          (fun index previous ↦
            step (Nat.pair parameter (Nat.pair index previous))) := by
  funext input
  unfold primitiveRecursion Nat.unpaired
  rw [recursionValue_eq_natRec]

/-- A beta code records the initial value, requested output, and every transition of a
primitive-recursive computation. -/
def BetaComputation (base step : ℕ → ℕ)
    (parameter length output code : ℕ) : Prop :=
  sequenceAccessor code 0 = base parameter ∧
    sequenceAccessor code length = output ∧
      ∀ index < length,
        sequenceAccessor code (index + 1) =
          step (Nat.pair parameter
            (Nat.pair index (sequenceAccessor code index)))

/-- The bounded transition part of a beta computation.  The coordinates are code,
length, and the fixed recursion parameter, in that order. -/
def boundedBetaTransitions (step : ℕ → ℕ) :
    Set (Vector3 ℕ 3) :=
  {values | ∀ index < values &1,
    sequenceAccessor (values &0) (index + 1) =
      step (Nat.pair (values &2)
        (Nat.pair index (sequenceAccessor (values &0) index)))}

/-- The exact bounded-quantifier closure still needed from the MRDP source theorem. -/
def BoundedBetaTransitionsAreDiophantine : Prop :=
  ∀ {step : ℕ → ℕ},
    NatDiophFn step → Dioph (boundedBetaTransitions step)

/-- The beta computation graph, with output first and encoded input second, matching the
vector form of `DiophFn`. -/
def betaRecursionGraph (base step : ℕ → ℕ) :
    Set (Vector3 ℕ 2) :=
  {values | ∃ code,
    BetaComputation base step
      (Nat.unpair (values &1)).1 (Nat.unpair (values &1)).2
      (values &0) code}

/-- The full beta-recursion graph closure, retained as a convenient derived interface. -/
def BetaRecursionGraphsAreDiophantine : Prop :=
  ∀ {base step : ℕ → ℕ},
    NatDiophFn base → NatDiophFn step →
      Dioph (betaRecursionGraph base step)

/-- Every finite prefix of a primitive-recursive trajectory has a beta code satisfying
the complete transition relation. -/
theorem exists_betaComputation (base step : ℕ → ℕ)
    (parameter length : ℕ) :
    ∃ code, BetaComputation base step parameter length
      (recursionValue base step parameter length) code := by
  let values : Fin (length + 1) → ℕ :=
    fun index ↦ recursionValue base step parameter index
  obtain ⟨code, hcode⟩ := exists_sequenceCode_fin values
  refine ⟨code, ?_, ?_, ?_⟩
  · simpa [values] using hcode (0 : Fin (length + 1))
  · simpa [values] using hcode ⟨length, by omega⟩
  · intro index hindex
    have hcurrent :
        sequenceAccessor code index =
          recursionValue base step parameter index := by
      simpa [values] using hcode ⟨index, by omega⟩
    have hnext :
        sequenceAccessor code (index + 1) =
          recursionValue base step parameter (index + 1) := by
      simpa [values] using hcode ⟨index + 1, by omega⟩
    calc
      sequenceAccessor code (index + 1) =
          recursionValue base step parameter (index + 1) := hnext
      _ = step (Nat.pair parameter
          (Nat.pair index (recursionValue base step parameter index))) := rfl
      _ = step (Nat.pair parameter
          (Nat.pair index (sequenceAccessor code index))) := by rw [hcurrent]

/-- Any beta sequence satisfying the initial and transition equations has the unique
primitive-recursive output. -/
theorem output_eq_recursionValue_of_betaComputation
    {base step : ℕ → ℕ} {parameter length output code : ℕ}
    (hcomputation : BetaComputation base step parameter length output code) :
    output = recursionValue base step parameter length := by
  have hsequence : ∀ index, index ≤ length →
      sequenceAccessor code index = recursionValue base step parameter index := by
    intro index hindex
    induction index with
    | zero => exact hcomputation.1
    | succ index ih =>
        calc
          sequenceAccessor code (index + 1) =
              step (Nat.pair parameter
                (Nat.pair index (sequenceAccessor code index))) :=
            hcomputation.2.2 index (by omega)
          _ = step (Nat.pair parameter
                (Nat.pair index (recursionValue base step parameter index))) := by
            rw [ih (by omega)]
          _ = recursionValue base step parameter (index + 1) := rfl
  calc
    output = sequenceAccessor code length := hcomputation.2.1.symm
    _ = recursionValue base step parameter length := hsequence length le_rfl

/-- The beta computation graph has exactly the graph semantics of primitive recursion. -/
theorem betaRecursionGraph_iff (base step : ℕ → ℕ)
    (values : Vector3 ℕ 2) :
    betaRecursionGraph base step values ↔
      primitiveRecursion base step (values &1) = values &0 := by
  let parameter := (Nat.unpair (values &1)).1
  let length := (Nat.unpair (values &1)).2
  constructor
  · rintro ⟨code, hcode⟩
    have houtput := output_eq_recursionValue_of_betaComputation hcode
    exact houtput.symm
  · intro houtput
    obtain ⟨code, hcode⟩ := exists_betaComputation base step parameter length
    refine ⟨code, ?_⟩
    have hvalue : recursionValue base step parameter length = values &0 := houtput
    rw [← hvalue]
    exact hcode

/-- Bounded-transition closure supplies the complete beta-recursion graph.  All other
conditions are ordinary Diophantine function composition, conjunction, and one existential
witness for the beta code. -/
theorem betaRecursionGraphsAreDiophantine_of_boundedTransitions
    (bounded : BoundedBetaTransitionsAreDiophantine) :
    BetaRecursionGraphsAreDiophantine := by
  intro base step hbase hstep
  have hcode :
      DiophFn fun values : Vector3 ℕ 3 ↦ values &0 := D&0
  have houtput :
      DiophFn fun values : Vector3 ℕ 3 ↦ values &1 := D&1
  have hinput :
      DiophFn fun values : Vector3 ℕ 3 ↦ values &2 := D&2
  have hparameter :
      DiophFn fun values : Vector3 ℕ 3 ↦ (Nat.unpair (values &2)).1 :=
    natUnpair_fst_comp_diophFn hinput
  have hlength :
      DiophFn fun values : Vector3 ℕ 3 ↦ (Nat.unpair (values &2)).2 :=
    natUnpair_snd_comp_diophFn hinput
  have haccessorZero :
      DiophFn fun values : Vector3 ℕ 3 ↦ sequenceAccessor (values &0) 0 :=
    Dioph.diophFn_comp sequenceAccessor_diophFn
      [fun values : Vector3 ℕ 3 ↦ values &0, fun _ ↦ 0]
      ⟨hcode, Dioph.const_dioph 0⟩
  have haccessorLength :
      DiophFn fun values : Vector3 ℕ 3 ↦
        sequenceAccessor (values &0) (Nat.unpair (values &2)).2 :=
    Dioph.diophFn_comp sequenceAccessor_diophFn
      [fun values : Vector3 ℕ 3 ↦ values &0,
        fun values ↦ (Nat.unpair (values &2)).2]
      ⟨hcode, hlength⟩
  have hbaseValue :
      DiophFn fun values : Vector3 ℕ 3 ↦
        base (Nat.unpair (values &2)).1 :=
    Dioph.diophFn_comp hbase
      [fun values ↦ (Nat.unpair (values &2)).1] hparameter
  have htransitions :
      Dioph fun values : Vector3 ℕ 3 ↦
        ∀ index < (Nat.unpair (values &2)).2,
          sequenceAccessor (values &0) (index + 1) =
            step (Nat.pair (Nat.unpair (values &2)).1
              (Nat.pair index (sequenceAccessor (values &0) index))) := by
    exact Dioph.dioph_comp (bounded hstep)
      [fun values : Vector3 ℕ 3 ↦ values &0,
        fun values ↦ (Nat.unpair (values &2)).2,
        fun values ↦ (Nat.unpair (values &2)).1]
      ⟨hcode, hlength, hparameter⟩
  have hwitness :
      Dioph fun values : Vector3 ℕ 3 ↦
        BetaComputation base step (Nat.unpair (values &2)).1
          (Nat.unpair (values &2)).2 (values &1) (values &0) := by
    exact (haccessorZero D= hbaseValue) D∧
      ((haccessorLength D= houtput) D∧ htransitions)
  apply Dioph.ext ((D∃) 2 hwitness)
  intro values
  rfl

/-- Bounded beta-transition closure supplies the primitive-recursion constructor. -/
theorem primitiveRecursion_diophFn
    (bounded : BoundedBetaTransitionsAreDiophantine)
    {base step : ℕ → ℕ} (hbase : NatDiophFn base)
    (hstep : NatDiophFn step) :
    NatDiophFn (primitiveRecursion base step) := by
  apply (Dioph.diophFn_vec _).2
  have hgraph :=
    betaRecursionGraphsAreDiophantine_of_boundedTransitions bounded hbase hstep
  exact Dioph.ext hgraph (betaRecursionGraph_iff base step)

/-- Pairing two unary Diophantine functions preserves Diophantineness. -/
theorem natPair_diophFn {left right : ℕ → ℕ}
    (hleft : NatDiophFn left) (hright : NatDiophFn right) :
    NatDiophFn fun input ↦ Nat.pair (left input) (right input) := by
  unfold NatDiophFn at hleft hright ⊢
  exact natPair_comp_diophFn hleft hright

/-- Composition of unary Diophantine functions preserves Diophantineness. -/
theorem natComp_diophFn {outer inner : ℕ → ℕ}
    (houter : NatDiophFn outer) (hinner : NatDiophFn inner) :
    NatDiophFn fun input ↦ outer (inner input) := by
  unfold NatDiophFn at houter hinner ⊢
  exact Dioph.diophFn_comp houter
    [fun values : Vector3 ℕ 1 ↦ inner (values &0)] hinner

/-- Subject only to bounded beta-transition closure, every unary primitive-recursive function
is Diophantine.  All non-recursive constructors are discharged concretely here. -/
theorem natPrimrec_diophFn
    (bounded : BoundedBetaTransitionsAreDiophantine)
    {function : ℕ → ℕ} (hfunction : Nat.Primrec function) :
    NatDiophFn function := by
  induction hfunction with
  | zero => exact Dioph.const_dioph 0
  | succ =>
      simpa [NatDiophFn, Nat.succ_eq_add_one] using ((D&0) D+ D.1)
  | left => exact natUnpair_fst_diophFn
  | right => exact natUnpair_snd_diophFn
  | pair _ _ hleft hright => exact natPair_diophFn hleft hright
  | comp _ _ houter hinner => exact natComp_diophFn houter hinner
  | prec _ _ hbase hstep =>
      rw [← primitiveRecursion_eq_unpaired]
      exact primitiveRecursion_diophFn bounded hbase hstep

end TrinomialUndecidability.Computability.MathlibDiophantinePrimrec
