import Trinomial.Encoding.Colength
import Trinomial.Encoding.Generators

/-!
# The binomial-coefficient bounds: `C(N+7,5)` generators, colength `C(N+6,4)`

[abstract and Corollary 5.1: "a computable family of ideals in one fixed
polynomial ring, with uniform bounds on colength, generator count, and generator degree";
proof of Theorem 4.5.]

The generator list `generators Q` of `Trinomial/Encoding/Generators.lean` consists of the products
`s^a t^b c^γ` of degree `5` (there are `C(N+6, 5)` of them) together with a basis of the
kernel of `ψ|_{W₄}`, which has at most `dim W₄ = C(N+6, 4)` elements, one for each product
of degree `≤ 4`.  So `I_P` is generated by at most `C(N+6,5) + C(N+6,4) = C(N+7,5)`
polynomials, each of total degree at most `5` (`generators_degree_le`).  Moreover
`ℚ[S,T,D]/I_P` is spanned by the classes of the products of degree `≤ 4`, because every
polynomial is `f_{≤4} + f_{≥5}` with `f_{≥5} ∈ 𝔪⁵ ⊆ I_P`; this gives the colength bound
`C(N+6, 4)` of Corollary 5.1, the first of the two bounds (the second,
`(N+5) + M(N+3)`, is `finrank_quotient_le` in `Trinomial/Encoding/Colength.lean`).

* `length_antidiagonalTuple` — there are `C(n+k−1, n)` exponent vectors `e : Fin k → ℕ`
  with `∑ e_i = n`;
* `length_exponentsEQ`, `length_exponentsLE`, `length_lowMonomials`,
  `length_exponentsEQ_five` — the numbers of products `s^a t^b c^γ` of degree `= d`, `≤ d`,
  `≤ 4`, `= 5`;
* `generators_length_le` — the generator count `C(N+7, 5)`;
* `finrank_quotient_le_choose`, `finrank_quotient_le_min` — the colength bound `C(N+6, 4)`.

The instances for the family `I_e` of Corollary 5.1
(`haltingGenerators_length_le_choose`, `finrank_haltingIdeal_le_choose`) are in
`Trinomial/Universal/HaltingFamily.lean`.
-/

set_option autoImplicit false

namespace Trinomial

variable {N M : ℕ}

/-! ### Counting exponent vectors -/

/-- The defining recurrence of `List.Nat.antidiagonalTuple` in the case of `k + 1` entries:
split off the first entry. -/
theorem antidiagonalTuple_succ_left (k n : ℕ) :
    List.Nat.antidiagonalTuple (k + 1) n = (List.Nat.antidiagonal n).flatMap
      fun ni => (List.Nat.antidiagonalTuple k ni.2).map (Fin.cons ni.1) := by
  rw [List.Nat.antidiagonalTuple]

/-- Pascal's rule for the number of `(k+1)`-tuples with sum `n+1`: either the first entry is
`0` and the remaining `k` entries sum to `n+1`, or the first entry is positive and lowering
it by one gives a `(k+1)`-tuple with sum `n`. -/
theorem length_antidiagonalTuple_succ_succ (k n : ℕ) :
    (List.Nat.antidiagonalTuple (k + 1) (n + 1)).length
      = (List.Nat.antidiagonalTuple k (n + 1)).length
        + (List.Nat.antidiagonalTuple (k + 1) n).length := by
  rw [antidiagonalTuple_succ_left k (n + 1), List.Nat.antidiagonal_succ, List.flatMap_cons,
    List.flatMap_map, List.length_append, antidiagonalTuple_succ_left k n, List.length_flatMap,
    List.length_flatMap]
  simp only [List.length_map, Prod.map_snd, id_eq]

/-- **The number of exponent vectors of degree `n`**: there are `C(n+k−1, n)` vectors
`e : Fin k → ℕ` with `∑ e_i = n` (for `k = 0` the formula reads `C(n−1, n)`, which is `1`
for `n = 0` and `0` otherwise). -/
theorem length_antidiagonalTuple (k n : ℕ) :
    (List.Nat.antidiagonalTuple k n).length = Nat.choose (n + k - 1) n := by
  induction k generalizing n with
  | zero =>
      cases n with
      | zero => rfl
      | succ n =>
          rw [List.Nat.antidiagonalTuple_zero_succ, List.length_nil,
            show n + 1 + 0 - 1 = n by omega, Nat.choose_eq_zero_of_lt (Nat.lt_succ_self n)]
  | succ k ihk =>
      induction n with
      | zero =>
          rw [List.Nat.antidiagonalTuple_zero_right, List.length_singleton, Nat.choose_zero_right]
      | succ n ihn =>
          rw [length_antidiagonalTuple_succ_succ, ihk, ihn,
            show n + 1 + k - 1 = n + k by omega, show n + (k + 1) - 1 = n + k by omega,
            show n + 1 + (k + 1) - 1 = n + k + 1 by omega, Nat.choose_succ_succ' (n + k) n]
          exact Nat.add_comm _ _

/-- There are `C(d+k−1, d)` products `s^a t^b c^γ` of degree exactly `d` in `k` variables. -/
theorem length_exponentsEQ (k d : ℕ) : (exponentsEQ k d).length = Nat.choose (d + k - 1) d :=
  length_antidiagonalTuple k d

/-- The exponent vectors of degree `≤ d + 1` are those of degree `≤ d` followed by those of
degree `d + 1`. -/
theorem exponentsLE_succ (k d : ℕ) :
    exponentsLE k (d + 1) = exponentsLE k d ++ exponentsEQ k (d + 1) := by
  unfold exponentsLE exponentsEQ
  rw [List.range_succ, List.flatMap_append, List.flatMap_singleton]

/-- There are `C(d+k, d)` products `s^a t^b c^γ` of degree `≤ d` in `k` variables. -/
theorem length_exponentsLE (k d : ℕ) : (exponentsLE k d).length = Nat.choose (d + k) d := by
  induction d with
  | zero =>
      rw [exponentsLE, List.range_one, List.flatMap_singleton, length_antidiagonalTuple,
        Nat.choose_zero_right, Nat.choose_zero_right]
  | succ d ih =>
      rw [exponentsLE_succ, List.length_append, ih, length_exponentsEQ,
        show d + 1 + k - 1 = d + k by omega, Nat.add_right_comm d 1 k, Nat.choose_succ_succ']

/-- `dim W₄ = C(N+6, 4)`: the number of products `s^a t^b c^γ` with `a + b + |γ| ≤ 4` in the
`N + 2` variables `s, t, c₁, …, c_N` [proof of Theorem 4.5: "the `C(N+6,4)` monomials of
degree at most four in these coordinates form a basis of `W`"]. -/
theorem length_lowMonomials (N : ℕ) : (lowMonomials N).length = Nat.choose (N + 6) 4 := by
  rw [lowMonomials, length_exponentsLE, show 4 + (2 + N) = N + 6 by omega]

/-- There are `C(N+6, 5)` products `s^a t^b c^γ` of degree `5` [proof of Theorem 4.5: "the
`C(N+6,5)` monomials of degree five generate `𝔪⁵`"]. -/
theorem length_exponentsEQ_five (N : ℕ) :
    (exponentsEQ (2 + N) 5).length = Nat.choose (N + 6) 5 := by
  rw [length_exponentsEQ, show 5 + (2 + N) - 1 = N + 6 by omega]

/-! ### The generator count -/

/-- **The generator count in closed form**: `I_P` is generated by the at most
`C(N+6,5) + C(N+6,4) = C(N+7,5)` polynomials of `generators Q`, each of total degree at most
`5` (`generators_degree_le`) [Corollary 5.1 ("uniform bounds on colength,
generator count, and generator degree"); proof of Theorem 4.5: "`I_P` is generated by at
most `C(N+6,5) + C(N+6,4) = C(N+7,5)` polynomials of total degree at most five"]. -/
theorem generators_length_le (Q : Fin M → BilinearFormMatrix (Option (Fin N))) :
    (generators Q).length ≤ Nat.choose (N + 7) 5 := by
  have hk := length_kernelBasis_le (rows Q)
  have h5 := length_exponentsEQ_five N
  have h4 := length_lowMonomials N
  have h7 : Nat.choose (N + 7) 5 = Nat.choose (N + 6) 4 + Nat.choose (N + 6) 5 :=
    Nat.choose_succ_succ' (N + 6) 4
  rw [generators, List.length_append, List.length_map, List.length_map]
  omega

/-! ### The colength bound `C(N+6, 4)` -/

/-- The `ℚ`-linear map `ℚ^{C(N+6,4)} → ℚ[S,T,D]/I_P`, `v ↦ [∑ⱼ vⱼ s^{aⱼ} t^{bⱼ} c^{γⱼ}]`:
`lowCombination` followed by the quotient map. -/
noncomputable def lowCombinationQuotient (Q : Fin M → BilinearFormMatrix (Option (Fin N))) :
    (Fin (lowMonomials N).length → ℚ) →ₗ[ℚ] (MvPolynomial (Var N) ℚ ⧸ polyReductionIdeal Q) :=
  (Ideal.Quotient.mkₐ ℚ (polyReductionIdeal Q)).toLinearMap ∘ₗ lowCombination N

/-- The classes of the products `s^a t^b c^γ` of degree `≤ 4` span `ℚ[S,T,D]/I_P`: every
polynomial is `f_{≤4} + f_{≥5}` with `f_{≤4} ∈ W₄` and `f_{≥5} ∈ 𝔪⁵ ⊆ I_P`
[proof of Theorem 4.5: "`ℚ[S, T, D₁, …, D_N] = W ⊕ 𝔪⁵`", with `𝔪⁵ ⊆ I_P`]. -/
theorem lowCombinationQuotient_surjective (Q : Fin M → BilinearFormMatrix (Option (Fin N))) :
    Function.Surjective (lowCombinationQuotient Q) := by
  intro x
  obtain ⟨f, rfl⟩ := Ideal.Quotient.mk_surjective x
  obtain ⟨g, hg, hfg⟩ := exists_lowDegree_sub_mem_pow_five f
  obtain ⟨v, rfl⟩ := (Submodule.mem_span_range_iff_exists_fun ℚ).mp hg
  refine ⟨v, ?_⟩
  rw [lowCombinationQuotient, LinearMap.comp_apply, AlgHom.toLinearMap_apply,
    Ideal.Quotient.mkₐ_eq_mk, lowCombination_apply]
  exact (Ideal.Quotient.eq.mpr (span_pointGen_pow_five_le Q hfg)).symm

/-- **The colength bound `C(N+6, 4)`**: `dim_ℚ (ℚ[S,T,D]/I_P) ≤ dim_ℚ (ℚ[S,T,D]/𝔪⁵)`, the
number of monomials of degree `≤ 4` in `N+2` variables, for every ideal `I_P` of Theorem 4.5
[Corollary 5.1 ("uniform bounds on colength")]. -/
theorem finrank_quotient_le_choose (Q : Fin M → BilinearFormMatrix (Option (Fin N))) :
    Module.finrank ℚ (MvPolynomial (Var N) ℚ ⧸ polyReductionIdeal Q) ≤ Nat.choose (N + 6) 4 :=
  calc Module.finrank ℚ (MvPolynomial (Var N) ℚ ⧸ polyReductionIdeal Q)
      = Module.finrank ℚ (LinearMap.range (lowCombinationQuotient Q)) := by
        rw [LinearMap.range_eq_top.mpr (lowCombinationQuotient_surjective Q), finrank_top]
    _ ≤ Module.finrank ℚ (Fin (lowMonomials N).length → ℚ) := LinearMap.finrank_range_le _
    _ = Nat.choose (N + 6) 4 := by rw [Module.finrank_fin_fun, length_lowMonomials]

/-- Both colength bounds (Corollary 5.1 and the proof of Theorem 4.5):
`dim_ℚ (ℚ[S,T,D]/I_P) ≤ min { C(N+6, 4), (N+5) + M(N+3) }`. -/
theorem finrank_quotient_le_min (Q : Fin M → BilinearFormMatrix (Option (Fin N))) :
    Module.finrank ℚ (MvPolynomial (Var N) ℚ ⧸ polyReductionIdeal Q)
      ≤ min (Nat.choose (N + 6) 4) ((N + 5) + M * (N + 3)) :=
  le_min (finrank_quotient_le_choose Q) (finrank_quotient_le Q)

end Trinomial
