import Trinomial.Encoding.GuardedSystem

/-!
# The computable section of Lemma 4.2

[Lemma 4.2, second and third bullet].  Let `X ⊆ ℤ^r` be the common zero
set of a degree-≤2 system `L` in `r` variables and `X̂₁ ⊆ ℤ^{r+6}` the zero set of the
guarded system `guarded L` (the affine chart `t = 1` of the homogeneous guarded system).
The projection `π : X̂₁ → X`, `w ↦ w ∘ Fin.castAdd 6`, forgets the guard coordinates
`h, k, u₁, u₂, u₃, u₄`.  This module implements the section `s : X → X̂₁` of `π` described
in the proof of Lemma 4.2:

* `pellSolution B` — the first term `(h, k)` of the Pell solution sequence `pell3`
  generated by `2 + √3` with `h ≥ B`;
* `fourSquares n` — a four-squares witness `(u₁, u₂, u₃, u₄)` of `n`, found by exhaustive
  search over the box `{0, …, Nat.sqrt n}⁴`; the search never fails by Lagrange's
  four-squares theorem (`Nat.sum_four_squares`);
* `guardSection z = (z, h, k, u₁, u₂, u₃, u₄)` with `(h, k) = pellSolution (Σ zᵢ²)` and
  `(u₁, …, u₄) = fourSquares (h − Σ zᵢ²)`;
* `guardSection_castAdd` (`π ∘ s = id`), `guardSection_solves` (`s` maps `X` into `X̂₁`),
  `projection_surjective` (the second bullet of Lemma 4.2 with the explicit
  preimage), and `guarded_solvable_of_solvable` (the hard direction of
  `guarded_solvable_iff`, rederived from the section).

All definitions are executable; `Trinomial/Examples.lean` runs `pellSolution`, `fourSquares`,
and `guardSection` on small inputs.
-/

set_option autoImplicit false

namespace Trinomial

/-! ### The Pell solution  [proof of Lemma 4.2]

"Take for `(h, k)` the first term of the Pell solution sequence generated by `2 + √3` with
`h` large enough." -/

theorem exists_pell3_ge (B : ℤ) : ∃ n : ℕ, B ≤ (pell3 n).1 :=
  ⟨B.toNat, by have := pell3_growth B.toNat; have := Int.self_le_toNat B; omega⟩

/-- The index of the first term of the Pell solution sequence `pell3` with `h ≥ B`. -/
def pellIndex (B : ℤ) : ℕ := Nat.find (exists_pell3_ge B)

/-- The first term `(h, k)` of the Pell solution sequence generated by `2 + √3` with `h ≥ B`
[proof of Lemma 4.2]. -/
def pellSolution (B : ℤ) : ℤ × ℤ := pell3 (pellIndex B)

/-- `pellSolution B = (h, k)` satisfies `h² − 3k² = 1` and `h ≥ B`. -/
theorem pellSolution_spec (B : ℤ) :
    (pellSolution B).1 ^ 2 - 3 * (pellSolution B).2 ^ 2 = 1 ∧ B ≤ (pellSolution B).1 :=
  ⟨pell3_eq _, Nat.find_spec (exists_pell3_ge B)⟩

/-- `pellSolution B` is the *first* term with `h ≥ B`: every earlier term has `h < B`. -/
theorem pellSolution_first (B : ℤ) {n : ℕ} (hn : n < pellIndex B) : (pell3 n).1 < B :=
  not_le.mp (Nat.find_min (exists_pell3_ge B) hn)

/-! ### Four squares by exhaustive search  [proof of Lemma 4.2]

"Find the four-squares witness `(u₁, u₂, u₃, u₄)` by exhaustive search." -/

/-- The search box `{0, …, Nat.sqrt n}⁴` for four-squares witnesses of `n`. -/
def fourSquaresBox (n : ℕ) : List (ℕ × ℕ × ℕ × ℕ) :=
  List.range (Nat.sqrt n + 1) ×ˢ List.range (Nat.sqrt n + 1)
    ×ˢ List.range (Nat.sqrt n + 1) ×ˢ List.range (Nat.sqrt n + 1)

/-- Whether `(a, b, c, d)` is a four-squares witness of `n`, i.e. `a² + b² + c² + d² = n`. -/
def isFourSquares (n : ℕ) (q : ℕ × ℕ × ℕ × ℕ) : Bool :=
  q.1 ^ 2 + q.2.1 ^ 2 + q.2.2.1 ^ 2 + q.2.2.2 ^ 2 == n

/-- Exhaustive search for a four-squares witness of `n` in the box `fourSquaresBox n`. -/
def fourSquares? (n : ℕ) : Option (ℕ × ℕ × ℕ × ℕ) :=
  (fourSquaresBox n).find? (isFourSquares n)

/-- Every four-squares witness of `n` lies in the search box: each summand is `≤ Nat.sqrt n`. -/
theorem mem_fourSquaresBox {n a b c d : ℕ} (h : a ^ 2 + b ^ 2 + c ^ 2 + d ^ 2 = n) :
    (a, b, c, d) ∈ fourSquaresBox n := by
  simp only [fourSquaresBox, List.mem_product, List.mem_range, Nat.lt_succ_iff, Nat.le_sqrt']
  omega

/-- The exhaustive search never fails (Lagrange's four-squares theorem). -/
theorem fourSquares?_isSome (n : ℕ) : (fourSquares? n).isSome = true := by
  rw [fourSquares?, List.find?_isSome]
  obtain ⟨a, b, c, d, h⟩ := Nat.sum_four_squares n
  exact ⟨(a, b, c, d), mem_fourSquaresBox h, by simp [isFourSquares, h]⟩

/-- A four-squares witness `(u₁, u₂, u₃, u₄)` of `n`, found by exhaustive search
[proof of Lemma 4.2]. -/
def fourSquares (n : ℕ) : ℕ × ℕ × ℕ × ℕ := (fourSquares? n).get (fourSquares?_isSome n)

theorem fourSquares?_eq (n : ℕ) : fourSquares? n = some (fourSquares n) :=
  (Option.some_get (fourSquares?_isSome n)).symm

/-- `fourSquares n = (u₁, u₂, u₃, u₄)` satisfies `u₁² + u₂² + u₃² + u₄² = n`. -/
theorem fourSquares_spec (n : ℕ) :
    (fourSquares n).1 ^ 2 + (fourSquares n).2.1 ^ 2 + (fourSquares n).2.2.1 ^ 2
      + (fourSquares n).2.2.2 ^ 2 = n := by
  have h := List.find?_some (fourSquares?_eq n)
  simpa [isFourSquares] using h

/-! ### Completing a point of `X` by guard coordinates -/

variable {r : ℕ}

/-- The guard coordinates sit behind the `r` coordinates of `X`: `h` at `vh r`. -/
theorem append_vh (z : Fin r → ℤ) (v : Fin 6 → ℤ) : Fin.append z v (vh r) = v 0 :=
  Fin.append_right z v 0

/-- The guard coordinate `k` sits at `vk r`. -/
theorem append_vk (z : Fin r → ℤ) (v : Fin 6 → ℤ) : Fin.append z v (vk r) = v 1 :=
  Fin.append_right z v 1

/-- The guard coordinates `u₁, …, u₄` sit at `vu r 0, …, vu r 3`. -/
theorem append_vu (z : Fin r → ℤ) (v : Fin 6 → ℤ) (j : Fin 4) :
    Fin.append z v (vu r j) = ![v 2, v 3, v 4, v 5] j := by
  fin_cases j
  · exact Fin.append_right z v 2
  · exact Fin.append_right z v 3
  · exact Fin.append_right z v 4
  · exact Fin.append_right z v 5

/-- Guard coordinates `(h, k, u₁, …, u₄)` with `h² − 3k² = 1` and `Σ zᵢ² + Σ uⱼ² = h`
complete a solution `z` of `L` to a solution `(z, h, k, u₁, …, u₄)` of `guarded L`
[proof of Lemma 4.2].  (These are the points of the fiber `π⁻¹(z)`.) -/
theorem solves_guarded_append {L : List (DegreeTwoEquation r)} {z : Fin r → ℤ}
    (hz : Solves z L) {h k u₁ u₂ u₃ u₄ : ℤ} (hpell : h ^ 2 - 3 * k ^ 2 = 1)
    (hsq : (∑ i, z i * z i) + (u₁ ^ 2 + u₂ ^ 2 + u₃ ^ 2 + u₄ ^ 2) = h) :
    Solves (Fin.append z ![h, k, u₁, u₂, u₃, u₄]) (guarded L) := by
  rw [guarded, solves_append]
  refine ⟨fun F hF => ?_, fun F hF => ?_⟩
  · obtain ⟨G, hG, rfl⟩ := List.mem_map.mp hF
    rw [DegreeTwoEquation.eval_rename,
      show Fin.append z ![h, k, u₁, u₂, u₃, u₄] ∘ Fin.castAdd 6 = z from
        funext fun i => Fin.append_left _ _ i]
    exact hz G hG
  · rcases List.mem_cons.mp hF with rfl | hF'
    · rw [gPell_eval, append_vh, append_vk]
      simp only [Matrix.cons_val]
      linear_combination hpell
    · rw [List.mem_singleton] at hF'
      subst hF'
      rw [gSq_eval, append_vh, Fin.sum_univ_four]
      simp only [Fin.append_left, append_vu, Matrix.cons_val]
      linear_combination hsq

/-! ### The section `s : X → X̂₁`  [Lemma 4.2, third bullet] -/

/-- The computable section `s : X → X̂₁` of the projection `π` of Lemma 4.2
[proof of Lemma 4.2]: `s(z) = (z, h, k, u₁, u₂, u₃, u₄)`, where `(h, k)`
is the first Pell solution with `h ≥ Σ zᵢ²` and `(u₁, …, u₄)` the four-squares witness of
`Δ = h − Σ zᵢ² ≥ 0` found by exhaustive search.  The guard coordinates occupy the
positions `vh r, vk r, vu r 0, …, vu r 3` of `guarded`. -/
def guardSection (z : Fin r → ℤ) : Fin (r + 6) → ℤ :=
  let S := ∑ i, z i * z i
  let hk := pellSolution S
  let u := fourSquares (hk.1 - S).toNat
  Fin.append z ![hk.1, hk.2, u.1, u.2.1, u.2.2.1, u.2.2.2]

/-- `π ∘ s = id`: the section restores `z` in the first `r` coordinates. -/
theorem guardSection_castAdd (z : Fin r → ℤ) (i : Fin r) :
    guardSection z (Fin.castAdd 6 i) = z i :=
  Fin.append_left _ _ i

/-- `s` maps `X` into `X̂₁`: the image of a solution of `L` solves `guarded L`
[Lemma 4.2, third bullet]. -/
theorem guardSection_solves {L : List (DegreeTwoEquation r)} {z : Fin r → ℤ}
    (hz : Solves z L) : Solves (guardSection z) (guarded L) := by
  have hΔ : (0 : ℤ) ≤ (pellSolution (∑ i, z i * z i)).1 - ∑ i, z i * z i := by
    have := (pellSolution_spec (∑ i, z i * z i)).2
    omega
  have hu := congrArg (Nat.cast : ℕ → ℤ)
    (fourSquares_spec ((pellSolution (∑ i, z i * z i)).1 - ∑ i, z i * z i).toNat)
  push_cast at hu
  rw [Int.toNat_of_nonneg hΔ] at hu
  exact solves_guarded_append hz (pellSolution_spec _).1 (by linarith)

/-- **Lemma 4.2, second bullet:** the projection `π : X̂₁ → X` is
surjective, with the explicit preimage `guardSection z` of each `z ∈ X`. -/
theorem projection_surjective (L : List (DegreeTwoEquation r)) :
    ∀ z : Fin r → ℤ, Solves z L →
      ∃ w : Fin (r + 6) → ℤ, Solves w (guarded L) ∧ ∀ i, w (Fin.castAdd 6 i) = z i :=
  fun z hz => ⟨guardSection z, guardSection_solves hz, guardSection_castAdd z⟩

/-- The hard direction of `guarded_solvable_iff` (`X ≠ ∅ ⟹ X̂₁ ≠ ∅`), rederived from
the section. -/
theorem guarded_solvable_of_solvable (L : List (DegreeTwoEquation r)) :
    (∃ z : Fin r → ℤ, Solves z L) → ∃ w : Fin (r + 6) → ℤ, Solves w (guarded L) :=
  fun ⟨z, hz⟩ => ⟨guardSection z, guardSection_solves hz⟩

end Trinomial
