import Mathlib.NumberTheory.SumFourSquares
import Mathlib.NumberTheory.Zsqrtd.Basic
import Mathlib.NumberTheory.PellMatiyasevic
import Mathlib.Tactic

/-!
# The arithmetic of the Pell guard

[Lemma 4.2].  The two guard equations appended to the homogenized
system are

  `g_{m+1} = h² − 3k² − t²`   and   `g_{m+2} = Σ xᵢ² + u₁² + u₂² + u₃² + u₄² − h·t`.

This module provides their arithmetic content:

* `pell_guard_at_infinity` — on `{t = 0}` the first guard forces `h = k = 0`
  (`3` is not a rational square);
* `pell3`, `pell_solution_large` — "the Pell solution sequence generated by `2 + √3`"
  is mathlib's sequence `Pell.xn`, `Pell.yn` for `a = 2` (so `d = a² − 1 = 3`), and the
  Pell equation `h² − 3k² = 1` has integral solutions with `h` arbitrarily large
  (`Pell.pell_eq`, `Pell.n_lt_xn`);
* `four_squares_int` — Lagrange's four-square theorem for nonnegative integers,
  which completes any affine solution through the second guard.
-/

set_option autoImplicit false

namespace Trinomial

/-- `1 < 2`, the hypothesis under which mathlib's `Pell.xn`, `Pell.yn` describe the solutions
of `x² − (a² − 1) y² = 1` for `a = 2`. -/
theorem one_lt_two' : 1 < 2 := by norm_num

/-- The Pell solution sequence generated by `2 + √3` [proof of Lemma 4.2]:
`(h, k) = (Pell.xn n, Pell.yn n)` for `a = 2`, i.e. `(1, 0), (2, 1), (7, 4), (26, 15), …`,
with `(h, k) ↦ (2h + 3k, h + 2k)`. -/
def pell3 (n : ℕ) : ℤ × ℤ := ((Pell.xn one_lt_two' n : ℤ), (Pell.yn one_lt_two' n : ℤ))

theorem pell3_eq (n : ℕ) : (pell3 n).1 ^ 2 - 3 * (pell3 n).2 ^ 2 = 1 := by
  have h := Pell.pell_eqz one_lt_two' n
  change (Pell.xn one_lt_two' n : ℤ) * Pell.xn one_lt_two' n
    - ((3 : ℕ) : ℤ) * Pell.yn one_lt_two' n * Pell.yn one_lt_two' n = 1 at h
  simp only [pell3]
  push_cast at h
  linear_combination h

/-- The solutions grow: `n < h_n` (`Pell.n_lt_xn`). -/
theorem pell3_growth (n : ℕ) : (n : ℤ) ≤ (pell3 n).1 := by
  simp only [pell3]
  exact_mod_cast (Pell.n_lt_xn one_lt_two' n).le

/-- The Pell equation `h² − 3k² = 1` has integral solutions with `h` arbitrarily large
[Lemma 4.2, via Barbeau]. -/
theorem pell_solution_large (B : ℤ) : ∃ h k : ℤ, h ^ 2 - 3 * k ^ 2 = 1 ∧ B ≤ h := by
  refine ⟨(pell3 B.toNat).1, (pell3 B.toNat).2, pell3_eq _, ?_⟩
  have h1 := pell3_growth B.toNat
  have h2 : B ≤ (B.toNat : ℤ) := Int.self_le_toNat B
  omega

/-- `3` is not a square, in the form mathlib's `Zsqrtd` theory needs. -/
instance : Zsqrtd.Nonsquare 3 :=
  ⟨fun n h => by
    rcases (by omega : n ≤ 1 ∨ 2 ≤ n) with h1 | h2
    · interval_cases n <;> omega
    · nlinarith⟩

/-- On the hyperplane at infinity the Pell guard has only the trivial solution:
`h² = 3k²` forces `h = k = 0`, because `3` is not a rational square
[proof of Lemma 4.2]; this is `Zsqrtd.divides_sq_eq_zero_z`. -/
theorem pell_guard_at_infinity {h k : ℤ} (hyp : h ^ 2 - 3 * k ^ 2 = 0) :
    h = 0 ∧ k = 0 :=
  Zsqrtd.divides_sq_eq_zero_z (d := 3) (by push_cast; linear_combination hyp)

/-- Lagrange's four-square theorem for nonnegative integers
[proof of Lemma 4.2]. -/
theorem four_squares_int (n : ℤ) (hn : 0 ≤ n) :
    ∃ a b c d : ℤ, a ^ 2 + b ^ 2 + c ^ 2 + d ^ 2 = n := by
  obtain ⟨a, b, c, d, habcd⟩ := Nat.sum_four_squares n.toNat
  refine ⟨a, b, c, d, ?_⟩
  have hcast : ((a ^ 2 + b ^ 2 + c ^ 2 + d ^ 2 : ℕ) : ℤ) = ((n.toNat : ℕ) : ℤ) := by
    exact_mod_cast congrArg (Nat.cast : ℕ → ℤ) habcd
  push_cast at hcast
  rwa [Int.toNat_of_nonneg hn] at hcast

end Trinomial
